import { useState, useEffect, useCallback } from 'react';
import './App.css';
import type { Message, AuditRecord, MemoryEntry, ResearchResponse } from './types';
import { submitResearchQueryStream, createMailDraft, saveMemory, getAuditRecord, listMemory, deleteMemory } from './api';
import type { ConversationTurn } from './api';
import ConversationPanel from './components/ConversationPanel';
import ToolTracePanel from './components/ToolTracePanel';
import MemoryPanel from './components/MemoryPanel';

/** Extracts an email address from a natural language message, or null if not found. */
function extractEmailAddress(text: string): string | null {
  const match = text.match(/[\w.+-]+@[\w-]+\.[a-z]{2,}/i);
  return match ? match[0] : null;
}

/** Formats a ResearchResponse into a plain-text email body. */
function formatEmailBody(question: string, response: ResearchResponse): string {
  const refs = response.references
    .map((r, i) => `${i + 1}. ${r.citation}${r.url ? ` — ${r.url}` : ''}`)
    .join('\n');

  return [
    'Dear Colleague,',
    '',
    'Please find below a research summary for the following question:',
    `"${question}"`,
    '',
    '── SUMMARY ──',
    response.summary,
    '',
    '── SYNTHESIS & INTERPRETATION ──',
    response.synthesisAndInterpretation,
    '',
    '── CONFIDENCE & GAPS ──',
    response.confidenceAndGaps,
    ...(refs ? ['', '── REFERENCES ──', refs] : []),
    '',
    '─────────────────────────────────────────',
    'Generated by Pharmaceutical Research Assistant.',
    'This is a draft — please review carefully before sending.',
  ].join('\n');
}

let messageCounter = 0;
function nextId() {
  return `msg-${++messageCounter}`;
}

export default function App() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [lastInteractionId, setLastInteractionId] = useState<string | null>(null);
  const [auditRecord, setAuditRecord] = useState<AuditRecord | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [memoryEntries, setMemoryEntries] = useState<MemoryEntry[]>([]);
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
  const [bottomCollapsed, setBottomCollapsed] = useState(false);
  const [auditLoading, setAuditLoading] = useState(false);

  const refreshMemory = useCallback(async () => {
    try {
      const result = await listMemory();
      setMemoryEntries(result.entries);
    } catch {
      // Memory is optional; silently ignore fetch failures
    }
  }, []);

  useEffect(() => {
    void refreshMemory();
  }, [refreshMemory]);

  useEffect(() => {
    if (!lastInteractionId) return;
    setAuditLoading(true);
    getAuditRecord(lastInteractionId)
      .then(setAuditRecord)
      .catch(() => setAuditRecord(null))
      .finally(() => setAuditLoading(false));
  }, [lastInteractionId]);

  const handleSubmit = useCallback(
    (question: string) => {
      const userMessage: Message = {
        id: nextId(),
        role: 'user',
        content: question,
        timestamp: new Date().toISOString(),
      };
      setMessages((prev) => [...prev, userMessage]);
      setIsLoading(true);
      setError(null);

      // --- Email intent: detect "email/send … to <address>" pattern ---
      const emailAddress = extractEmailAddress(question);
      const isEmailIntent =
        emailAddress !== null &&
        /\b(email|send|mail)\b/i.test(question);

      if (isEmailIntent) {
        // Find the most recent research response in the conversation
        const lastResearch = [...messages]
          .reverse()
          .find(
            (m) =>
              m.role === 'agent' &&
              typeof m.content === 'object' &&
              m.content.type === 'response',
          );

        if (!lastResearch || typeof lastResearch.content !== 'object' || lastResearch.content.type !== 'response') {
          setError('No research response found to email. Please run a research query first.');
          setMessages((prev) => prev.filter((m) => m !== userMessage));
          setIsLoading(false);
          return;
        }

        const researchContent = lastResearch.content as ResearchResponse;
        // Use the last user question as the subject source
        const lastUserQ = [...messages]
          .reverse()
          .find((m) => m.role === 'user' && typeof m.content === 'string');
        const subjectQuestion =
          typeof lastUserQ?.content === 'string' ? lastUserQ.content : 'Research Summary';
        const subject = `Research Summary: ${subjectQuestion.slice(0, 80)}`;
        const body = formatEmailBody(subjectQuestion, researchContent);

        // Extract citations for audit trail
        const citations = researchContent.references.map((r) => ({
          type: 'url' as const,
          id: r.url || r.id,
          title: r.citation,
        }));

        createMailDraft(emailAddress, subject, body, citations)
          .then((result) => {
            const draftMessage: Message = {
              id: nextId(),
              role: 'agent',
              content: { type: 'draft', draft: result.draft },
              timestamp: new Date().toISOString(),
            };
            setMessages((prev) => [...prev, draftMessage]);
          })
          .catch((err: Error) => {
            setError(err.message);
          })
          .finally(() => {
            setIsLoading(false);
          });

        return;
      }

      // --- Normal research path ---

      // Build history from current messages for multi-turn context
      const history: ConversationTurn[] = [];
      for (const m of messages) {
        if (m.role === 'user' && typeof m.content === 'string') {
          history.push({ role: 'user', content: m.content });
        } else if (m.role === 'agent' && typeof m.content === 'object' && m.content.type === 'response') {
          history.push({ role: 'assistant', content: (m.content as import('./types').ResearchResponse).summary });
        }
      }

      const streamingId = nextId();
      const streamingMsg: Message = {
        id: streamingId,
        role: 'streaming',
        content: '',
        timestamp: new Date().toISOString(),
        streamingStatus: 'Starting research…',
      };
      setMessages((prev) => [...prev, streamingMsg]);

      submitResearchQueryStream(
        question,
        undefined,
        history.length > 0 ? history : undefined,
        {
          onStatus: ({ message: msg }) => {
            setMessages((prev) =>
              prev.map((m) => (m.id === streamingId ? { ...m, streamingStatus: msg ?? 'Working…' } : m)),
            );
          },
          onToken: (chunk) => {
            setMessages((prev) =>
              prev.map((m) =>
                m.id === streamingId ? { ...m, content: (m.content as string) + chunk } : m,
              ),
            );
          },
          onComplete: (response) => {
            setMessages((prev) =>
              prev.map((m) =>
                m.id === streamingId
                  ? { id: streamingId, role: 'agent', content: response, timestamp: new Date().toISOString() }
                  : m,
              ),
            );
            if (response.type === 'response' && response.interactionId) {
              setLastInteractionId(response.interactionId);
            }
            setIsLoading(false);
          },
          onError: (err) => {
            setError(err.message);
            setMessages((prev) => prev.filter((m) => m.id !== streamingId));
            setIsLoading(false);
          },
        },
      );
    },
    [messages],
  );

  const handleDeleteMemory = useCallback(async (id: string) => {
    try {
      await deleteMemory(id);
      setMemoryEntries((prev) => prev.filter((e) => e.id !== id));
    } catch (err) {
      const msg = err instanceof Error ? err.message : 'Failed to delete memory entry.';
      setError(msg);
    }
  }, []);

  const handleSaveToMemory = useCallback(async (response: ResearchResponse) => {
    const title = response.summary.slice(0, 80).trimEnd() + (response.summary.length > 80 ? '…' : '');
    const content = [response.summary, '', response.synthesisAndInterpretation].join('\n\n');
    const citations = response.references.map((r) => ({
      type: (r.id.startsWith('PMID:') ? 'pmid' : r.id.startsWith('NCT') ? 'nct' : 'url') as 'pmid' | 'nct' | 'url',
      id: r.id,
      title: r.citation,
    }));
    await saveMemory(title, content, citations);
    await refreshMemory();
  }, [refreshMemory]);

  return (
    <div className="app-layout">
      <header className="app-header">
        <span>🔬</span>
        Pharmaceutical Research Assistant
        {messages.length > 0 && (
          <button
            className="new-research-btn"
            onClick={() => {
              setMessages([]);
              setLastInteractionId(null);
              setAuditRecord(null);
              setError(null);
            }}
            aria-label="Start new research"
          >
            + New Research
          </button>
        )}
      </header>

      {error && (
        <div className="error-banner">
          <span>⚠ {error}</span>
          <button onClick={() => setError(null)} aria-label="Dismiss error">✕</button>
        </div>
      )}

      <div className="app-body">
        <div className="app-main">
          <ConversationPanel
            messages={messages}
            isLoading={isLoading}
            onSubmit={handleSubmit}
            onSaveToMemory={handleSaveToMemory}
          />

          <div className={`app-bottom${bottomCollapsed ? ' collapsed' : ''}`}>
            <MemoryPanel
              entries={memoryEntries}
              onDelete={handleDeleteMemory}
              onRefresh={refreshMemory}
              collapsed={bottomCollapsed}
              onToggleCollapse={() => setBottomCollapsed((v) => !v)}
            />
          </div>
        </div>

        <div className={`app-sidebar${sidebarCollapsed ? ' collapsed' : ''}`}>
          <ToolTracePanel
            auditRecord={auditRecord}
            isLoading={auditLoading}
            collapsed={sidebarCollapsed}
            onToggleCollapse={() => setSidebarCollapsed((v) => !v)}
          />
        </div>
      </div>
    </div>
  );
}
